#### Variable labels for latex output ####

setFixest_dict(c(emp = "Persons Employed in Coal", employed = "Employed Persons",
                 uer = "Unemployment Rate", active_mines = "Active Mines", 
                 p_inc_1000 = "County Personal Income (PI) in USD Millions", 
                 p_inc_X = "County Personal Income (PI) in USD Billions",
                 pop_1000 = "County Population (Thousands)", 
                 fips = "County FIPS Code", year = "Year",
                 lag_mines = "Active Mines (t-1)",  lag_mines2 = "Active Mines (t-2)",
                 lag_mines3 = "Active Mines (t-3)",lag_mines4 = "Active Mines (t-4)",
                 mines_diff = "Change Active Mines", lag_diff = "Change Active Mines (t-1)",
                 lag_diff2 = "Change Active Mines (t-2)", lag_diff3 = "Change Active Mines (t-3)",
                 diff_emp = "Change Persons Employed in Coal",
                 lag_diff_emp = "Change Persons Employed in Coal (t-1)",
                 lag_diff_emp2 = "Change Persons Employed in Coal (t-2)",
                 diff_employed = "Change Employed Persons", 
                 diff_uer = "Change Unemployment Rate",
                 green_emp = "Persons Employed in Green Sectors",
                 diff_green_emp = "Change Persons Employed in Green Sectors",
                 lag_emp = "Persons Employed in Coal (t-1)",
                 lag_emp2 = "Persons Employed in Coal (t-2)",
                 ff_emp = "Persons Employed in FF (not incl. Coal)",
                 diff_ff_emp = "Change Persons Employed in FF (not incl. Coal)",
                 lag_diff_ffemp = "Change Persons Employed in FF (not incl. Coal) (t-1)",
                 lag_diff_ffemp2 = "Change Persons Employed in FF (not incl. Coal) (t-2)",
                 diff_total_ff_emp = "Change Persons Employed in FF (incl. Coal)",
                 lag_diff_total_ffemp = "Change Persons Employed in FF (incl. Coal) (t-1)",
                 lag_diff_total_ffemp2 = "Change Persons Employed in FF (incl. Coal) (t-2)",
                 type_factor1 = "Type 1",  type_factor2 = "Type 2", type_factor3 = "Type 3",
                 mine_closure = "Mine Closed (t)", lag_closure = "Mine Closed (t-1)",
                 ruc_bin = "Rural",
                 REE_inv_scaled_pinc = "REE Investments (Proportion of County PI)",
                 logrealgdp_pc = "Real GDP per capita (log)",
                 diff_log_realgdp_pc = "Change in (log) Real GDPPC",
                 log_pop = "Population (log)",
                 log_realgdp = "Real GDP (log)",
                 diff_log_employed = "Change in Employed Persons (log)",
                 diff_log_unemployed = "Change in Unemployed Persons (log)",
                 diff_log_pop = "Change in Population (log)",
                 diff_log_lf = "Change in Labour Force (log)",
                 diff_log_realgdp = "Change in Real GDP (log)",
                 prod_diff = "Change in Production (short tons)",
                 lag_prod_diff = "Change in Production (short tons) (t-1)",
                 lag_prod_diff2 = "Change in Production (short tons) (t-2)",
                 factor_type1 = "Type 1",
                 factor_type2 = "Type 2",
                 factor_type3 = "Type 3",
                 `f(mines_diff,1)` = "Change Active Mines (t+1)",
                  emp_10 = 'NAICS 10 \n All industries',                                                                  
                  emp_22 = 'NAICS 22 \n Utilities',                                                                        
                  emp_23 = 'NAICS 23 \n Construction',                                                                     
                  emp_42 = 'NAICS 42 \n Wholesale trade',                                                                  
                  emp_51 = 'NAICS 51 \n Information',                                                                      
                  emp_52 = 'NAICS 52 \n Finance and \n insurance',                                                            
                  emp_53 = 'NAICS 53 \n Real estate and \n rental and leasing',                                               
                  emp_54 = 'NAICS 54 \n Professional, scientific, \n and technical services',                                 
                  emp_71 = 'NAICS 71 \n Arts, entertainment, \n and recreation',                                              
                  emp_72 = 'NAICS 72 \n Accommodation \n and food services',                                                  
                  emp_81 = 'NAICS 81 \n Other services \n (except public administration)',                                    
                  emp_92 = 'NAICS 92 \n Public administration',                                                            
                  emp_11 = 'NAICS 11 \n Agriculture, forestry, \n fishing and hunting',                                       
                  emp_21 = 'NAICS 21 \n Mining, quarrying, and \n oil and gas extraction',                                    
                  emp_55 = 'NAICS 55 \n Management of companies \n and enterprises',                                          
                  emp_56 = 'NAICS 56 \n Administrative and \n support and waste management \n and remediation services',         
                  emp_61 = 'NAICS 61 \n Educational \n services',                                                             
                  emp_62 = 'NAICS 62 \n Health care and \n social assistance',                                                
                  log_emp_10 = 'NAICS 10 \n All industries',                                                              
                  log_emp_22 = 'NAICS 22 \n Utilities',                                                                    
                  log_emp_23 = 'NAICS 23 \n Construction',                                                                 
                  log_emp_42 = 'NAICS 42 \n Wholesale trade',                                                              
                  log_emp_51 = 'NAICS 51 \n Information',                                                                  
                  log_emp_52 = 'NAICS 52 \n Finance and insurance',                                                        
                  log_emp_53 = 'NAICS 53 \n Real estate and \n rental and leasing',                                           
                  log_emp_54 = 'NAICS 54 \n Professional, scientific, \n and technical services',                             
                  log_emp_71 = 'NAICS 71 \n Arts, entertainment, \n and recreation',                                          
                  log_emp_72 = 'NAICS 72 \n Accommodation \n and food services',                                              
                  log_emp_81 = 'NAICS 81 \n Other services \n (except public administration)',                                
                  log_emp_92 = 'NAICS 92 \n Public administration',                                                        
                  log_emp_11 = 'NAICS 11 \n Agriculture, forestry, \n fishing and hunting',                                   
                  log_emp_21 = 'NAICS 21 \n Mining, quarrying, and \n oil and gas extraction',                                
                  log_emp_55 = 'NAICS 55 \n Management of companies \n and enterprises',                                      
                  log_emp_56 = 'NAICS 56 \n Administrative and \n support and waste management \n and remediation services',     
                  log_emp_61 = 'NAICS 61 \n Educational \n services',                                                         
                  log_emp_62 = 'NAICS 62 \n Health care and \n social assistance',                                            
                  diff_emp_10 = 'NAICS 10 \n All industries',                                                             
                  diff_emp_22 = 'NAICS 22 \n Utilities',                                                                   
                  diff_emp_23 = 'NAICS 23 \n Construction',                                                                
                  diff_emp_42 = 'NAICS 42 \n Wholesale trade',                                                             
                  diff_emp_51 = 'NAICS 51 \n Information',                                                                 
                  diff_emp_52 = 'NAICS 52 \n Finance and insurance',                                                       
                  diff_emp_53 = 'NAICS 53 \n Real estate \n and rental and leasing',                                          
                  diff_emp_54 = 'NAICS 54 \n Professional, scientific, \n and technical services',                            
                  diff_emp_71 = 'NAICS 71 \n Arts, \n entertainment, \n and recreation',                                         
                  diff_emp_72 = 'NAICS 72 \n Accommodation \n and food \n services',                                             
                  diff_emp_81 = 'NAICS 81 \n Other services \n (except public administration)',                               
                  diff_emp_92 = 'NAICS 92 \n Public administration',                                                       
                  diff_emp_11 = 'NAICS 11 \n Agriculture, forestry, \n fishing and hunting',                                  
                  diff_emp_21 = 'NAICS 21 \n Mining, quarrying, and \n oil and gas extraction',                               
                  diff_emp_55 = 'NAICS 55 \n Management of \n companies and \n enterprises',                                     
                  diff_emp_56 = 'NAICS 56 \n Administrative and support \n and waste management \n and remediation services',    
                  diff_emp_61 = 'NAICS 61 \n Educational \n services',                                                        
                  diff_emp_62 = 'NAICS 62 \n Health care \n and social \n assistance',                                           
                  diff_log_emp_10 = 'NAICS 10 \n All industries',                                                         
                  diff_log_emp_22 = 'NAICS 22 \n Utilities',                                                               
                  diff_log_emp_23 = 'NAICS 23 \n Construction',                                                            
                  diff_log_emp_42 = 'NAICS 42 \n Wholesale trade',                                                         
                  diff_log_emp_51 = 'NAICS 51 \n Information',                                                             
                  diff_log_emp_52 = 'NAICS 52 \n Finance and insurance',                                                   
                  diff_log_emp_53 = 'NAICS 53 \n Real estate \n and rental and leasing',                                      
                  diff_log_emp_54 = 'NAICS 54 \n Professional, scientific, \n and technical services',                        
                  diff_log_emp_71 = 'NAICS 71 \n Arts, \n entertainment, \n and recreation',                                     
                  diff_log_emp_72 = 'NAICS 72 \n Accommodation \n and food \n services',                                         
                  diff_log_emp_81 = 'NAICS 81 \n Other services \n (except public administration)',                           
                  diff_log_emp_92 = 'NAICS 92 \n Public administration',                                                   
                  diff_log_emp_11 = 'NAICS 11 \n Agriculture, forestry, \n fishing and hunting',                              
                  diff_log_emp_21 = 'NAICS 21 \n Mining, quarrying, and \n oil and gas extraction',                           
                  diff_log_emp_55 = 'NAICS 55 \n Management of \n companies and \n enterprises',                                 
                  diff_log_emp_56 = 'NAICS 56 \n Administrative and support \n and waste management \n and remediation services',
                  diff_log_emp_61 = 'NAICS 61 \n Educational \n services',                                                    
                  diff_log_emp_62 = 'NAICS 62 \n Health care \n and social \n assistance',
                  diff_emp_coal ="Coal mining \n & support \n activities",
                  diff_emp_coal_sales = "Coal mining & \n coal and other \n mineral and \n ore merchant \n wholesalers",
                  diff_emp_coal_ff_gen = "Coal mining, \n sales & fossil \n fuel electric \n power \n generation",
                  diff_emp_non_coal = "Total \n employment \n excluding \n mining and \n coal sales",
                  diff_log_emp_non_coal = "Total \n employment \n excluding \n mining and \n coal sales",
                  diff_log_emp_coal ="Coal mining \n & support \n activities",
                  diff_log_emp_coal_sales = "Coal mining & \n coal and other \n mineral and \n ore merchant \n wholesalers",
                  diff_log_emp_coal_ff_gen = "Coal mining, \n sales & fossil \n fuel electric \n power \n generation",
                  coal_share_emp = "Coal Employment Share",
                  coal_share_emp_interpol = "Coal Employment Share",
                  coal_share_emp_mean = "Coal Employment Share",
                  "coal_share_emp_mean_discrete2 - medium" = "Coal Employment Share (medium)",
                  "coal_share_emp_discrete2 - medium" = "Coal Employment Share (medium)",
                  "coal_share_emp_interpol_discrete2 - medium" = "Coal Employment Share (medium)",
                 "coal_share_emp_mean_discrete3-high" = "Coal Employment Share (high)",
                 "coal_share_emp_discrete3-high" = "Coal Employment Share (high)",
                 "coal_share_emp_interpol_discrete3-high" = "Coal Employment Share (high)",
                 uer_lag1 = "UER (t-1)",
                 dmines = "(FD) Active Mines",
                 mines_lag1 = "Active Mines (t-1)",
                 mines_lag2 = "Active Mines (t-2)",
                 dgdp = "(FD) log GDP",
                 duer = "Change Unemployment Rate"
))


# "42352" ~ Coal and other mineral and ore merchant wholesalers
# "213113" ~ Support activities for coal mining
# "2121" ~ Coal mining
# "221112" Fossil fuel electric power generation
# emp_coal = emp_2121 + emp_213113, # "213113" ~ Support activities for coal mining + "2121" ~ Coal mining
# emp_coal_sales = emp_coal + emp_42352, Above + # "42352" ~ Coal and other mineral and ore merchant wholesalers
# emp_coal_ff_gen = emp_coal_sales + emp_221112, Above + "221112" Fossil fuel electric power generation
         #emp_non_coal = emp_10 - emp_coal_sales) 

sum_dict <- c("Active Mines (no.)","Unemployment Rate","Employed Persons", 
              "Unemployed Persons", "Labour Force", "Population", 
              "Total USDA RE Investments in USD","Coal Production (in short tons)",
              "Real GDP","Real GDP Per Capita", "Rural-Urban Code", 
              "Rural-Urban (binary)","Total TAA Allocation in USD",
              "USDA RE Investments scaled by Real GDP")

sum_dict_trans <-  c("Δ Unemployment Rate", "Δ Active Mines","Δ (log) Real GDP", 
                     "Δ (log) Real GDP per capita", "Δ (log) Employed Persons",
                     "Δ (log) Unemployed Persons", "Δ (log) Labour Force", "Δ (log) Population", 
                     "REE ≥ .1% of GDP")

cm <- c('lag_diff2' = 'Δ Active Mines (t-2)',
        'lag_diff' = 'Δ Active Mines (t-1)', 
        'mines_diff' = 'Δ Active Mines')

plot_dict = c("f(mines_diff,3)" = "-3", "f(mines_diff,2)" = "-2", "f(mines_diff, 1)" = "-1", 
              "mines_diff" = "0", "lag_diff" = "+1", "lag_diff2" = "+2", "lag_diff3" = "+3",
              `factor_type1:mines_diff` = "0",
              `factor_type2:mines_diff` = "0",
              `factor_type3:mines_diff` = "0",
              `factor_type1:lag_diff` = "+1",
              `factor_type2:lag_diff` = "+1",
              `factor_type3:lag_diff` = "+1",
              `factor_type1:lag_diff2` = "+2",
              `factor_type2:lag_diff2` = "+2",
              `factor_type3:lag_diff2` = "+2",
              `factor_type1:f(mines_diff, 1)` = "-1",
              `factor_type2:f(mines_diff, 1)` = "-1",
              `factor_type3:f(mines_diff, 1)` = "-1",
              `factor_type1:lag_diff3` = "+3",
              `factor_type2:lag_diff3` = "+3",
              `factor_type3:lag_diff3` = "+3"
              )
